# Generated by Django 4.1.2 on 2023-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_url_project_img_url_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stacks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
