# Generated by Django 4.1.2 on 2023-05-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_stacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stacks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
