# Generated by Django 4.1.2 on 2022-10-28 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_date_created_category_cat_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_date_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_date_updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_uniqueID',
            new_name='uniqueID',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_date_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_last_updated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_uniqueID',
            new_name='uniqueID',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_altText',
            new_name='altText',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_date_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_hashtags',
            new_name='hashtags',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_last_updated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_uniqueId',
            new_name='uniqueId',
        ),
    ]
