# Generated by Django 4.1.2 on 2022-11-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_image_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
